# Generated by Django 3.2.5 on 2021-08-03 14:28

from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=30, null=True)),
                ('lng', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrashCan',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('size', models.EmailField(max_length=255, unique=True)),
                ('quantity', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trashCan.localisation')),
            ],
        ),
    ]
