# Generated by Django 3.2.5 on 2021-08-04 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210803_2337'),
        ('trashCan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashcan',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.company'),
        ),
        migrations.AlterField(
            model_name='trashcan',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trashCan.localisation'),
        ),
    ]
