# Generated by Django 3.2.5 on 2021-08-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trashCan', '0002_auto_20210804_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashcan',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
