# Generated by Django 3.2.5 on 2021-08-04 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trashCan', '0003_alter_trashcan_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashcan',
            name='quantity',
            field=models.IntegerField(max_length=30),
        ),
    ]
