# Generated by Django 3.2.5 on 2021-08-27 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trashCan', '0004_alter_trashcan_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashcan',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position', to='trashCan.localisation'),
        ),
        migrations.AlterField(
            model_name='trashcan',
            name='quantity',
            field=models.IntegerField(default=0, max_length=30),
        ),
    ]
